version: "3.9"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes: # Optional: Persist data across container restarts
      - mongodb_data:/data/db

volumes:
  mongodb_data: # Named volume for data persistence
